# To make sure that we do not clutter everything within the "Builds/(architecture)" directory,
# we want to have all targets be placed within "Builds/(architecture)/BundleBuild"
set(OUTPUT_DIRECTORY_ROOT "${CMAKE_CURRENT_BINARY_DIR}/BundleBuild")
set(OUTPUT_DIRECTORY_I_BOOT "${OUTPUT_DIRECTORY_ROOT}/initramfs")
set(OUTPUT_DIRECTORY_D_BOOT "${OUTPUT_DIRECTORY_ROOT}/boot")
set(OUTPUT_DIRECTORY_SYSTEM "${OUTPUT_DIRECTORY_ROOT}/system")
set(OUTPUT_DIRECTORY_RECVRY "${OUTPUT_DIRECTORY_ROOT}/recovery")

set(OUTPUT_DIRECTORY_TESTS "${CMAKE_CURRENT_BINARY_DIR}/TestBuilds")

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${OUTPUT_DIRECTORY_ROOT}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${OUTPUT_DIRECTORY_ROOT}")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${OUTPUT_DIRECTORY_ROOT}")

file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY_ROOT}")
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY_I_BOOT}")
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY_D_BOOT}")
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY_SYSTEM}")
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY_RECVRY}")
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY_TESTS}")

include(ProcessorCount)

include_directories("${CMAKE_CURRENT_SOURCE_DIR}/ALX_Includes")