CollectSources("${PROJECT_MODULE_ROOT}/init_process" InitSources)
CollectSources("${PROJECT_MODULE_ROOT}/root_main" RootInitSources)
CollectSources("${PROJECT_MODULE_ROOT}/svcmg" svcmg_Sources)
CollectSources("${PROJECT_MODULE_ROOT}/ipc" IPC_Sources)
CollectSources("${PROJECT_MODULE_ROOT}/ipc" IPC_Sources)

add_executable(init ${InitSources})
target_link_libraries(init PRIVATE alx64-static)
target_link_options(init PRIVATE -static)
SetTargetFilename(init "init")
SetTargetOutputDir(init "${OUTPUT_DIRECTORY_I_BOOT}")
CopyTarget(init "init" "${OUTPUT_DIRECTORY_RECVRY}")
CopyTarget(init "init" "${OUTPUT_DIRECTORY_RECVRY}")