set(BUILD_SHARED_LIBS ON  CACHE BOOL "" FORCE)
set(ZLIB_BUILD_SHARED ON  CACHE BOOL "" FORCE)
set(ZLIB_BUILD_STATIC ON CACHE BOOL "" FORCE)
add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/External/zlib")

CopyExternalTarget(zlibstatic libz.a ${OUTPUT_DIRECTORY_SYSTEM}/${BINARY_PREFIX})
CopyExternalTarget(zlibstatic libz.a ${OUTPUT_DIRECTORY_RECVRY}/${BINARY_PREFIX})
CopyExternalTarget(zlibstatic libz.a ${OUTPUT_DIRECTORY_I_BOOT}/${BINARY_PREFIX})

CopyExternalTarget(zlib libz.so ${OUTPUT_DIRECTORY_SYSTEM}/${BINARY_PREFIX})
CopyExternalTarget(zlib libz.so ${OUTPUT_DIRECTORY_RECVRY}/${BINARY_PREFIX})
CopyExternalTarget(zlib libz.so ${OUTPUT_DIRECTORY_I_BOOT}/${BINARY_PREFIX})

message(STATUS "CMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}")
message(STATUS "CMAKE_HOST_SYSTEM_PROCESSOR=${CMAKE_HOST_SYSTEM_PROCESSOR}")
message(STATUS "CMAKE_C_COMPILER_ARCHITECTURE_ID=${CMAKE_C_COMPILER_ARCHITECTURE_ID}")
message(STATUS "CMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME}")